#!/usr/bin/env python3
"""Build the narration and music mix for the demo video.

    python3 build-audio.py [--model voices/en-us-ryan-high.onnx]

1. Synthesizes one clip per narration sentence offline with Piper (cached in audio-cache/).
2. Measures each clip and writes src/audio-durations.js, which src/timeline.js uses to lay out
   beat and caption timings (so the video, captions and voice stay in sync).
3. Places the clips on the timeline, adds a very light room, normalizes the voice to -16 LUFS.
4. Generates the music bed with make-music.py, ducks it under speech, sets it to about -29 LUFS.
5. Mixes voice + music into out/audio/mix.wav (peak-limited) for render.mjs --audio.
"""
import argparse
import hashlib
import json
import os
import re
import subprocess
import sys

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
SR = 48000
LENGTH_SCALE = '1.05'
VOICE_LUFS = -16.0
MUSIC_LUFS = -29.0
DUCK_DB = -9.0  # music level during speech, relative to the gaps
CARD_BOOST_DB = 3.0  # extra lift on the title and end cards


def sh(cmd, **kw):
    return subprocess.run(cmd, check=True, **kw)


def timeline():
    js = ("const T=require('./src/timeline.js');console.log(JSON.stringify({D:T.DURATION,"
          "B:T.BEATS.map(b=>({id:b.id,scene:b.scene,start:b.start,end:b.end,speech:b.speech}))}))")
    # fresh process each time so a newly written audio-durations.js is picked up
    out = subprocess.run(['node', '-e', js], cwd=HERE, check=True, capture_output=True, text=True).stdout
    return json.loads(out)


def read_audio(path, channels=1):
    raw = subprocess.run(['ffmpeg', '-loglevel', 'error', '-i', path, '-f', 'f32le', '-ac', str(channels),
                          '-ar', str(SR), '-'], check=True, capture_output=True).stdout
    a = np.frombuffer(raw, dtype=np.float32)
    return a.reshape(-1, channels) if channels > 1 else a


def write_audio(path, a):
    ch = 1 if a.ndim == 1 else a.shape[1]
    sh(['ffmpeg', '-y', '-loglevel', 'error', '-f', 'f32le', '-ar', str(SR), '-ac', str(ch), '-i', '-',
        '-c:a', 'pcm_f32le', path], input=a.astype(np.float32).tobytes())


def duration(path):
    out = subprocess.run(['ffprobe', '-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', path],
                         check=True, capture_output=True, text=True).stdout
    return float(out.strip())


def lufs(path):
    err = subprocess.run(['ffmpeg', '-hide_banner', '-nostats', '-i', path, '-af', 'ebur128=peak=true', '-f', 'null', '-'],
                         capture_output=True, text=True).stderr
    summary = err[err.rfind('Summary:'):]
    i = float(re.search(r'I:\s+(-?[\d.]+) LUFS', summary).group(1))
    pk = re.search(r'Peak:\s+(-?[\d.inf]+) dBFS', summary)
    return i, (float(pk.group(1)) if pk else None)


def trim_silence(a, thresh=0.003):
    idx = np.where(np.abs(a) > thresh)[0]
    if len(idx) == 0:
        return a
    s = max(0, idx[0] - int(0.02 * SR))
    e = min(len(a), idx[-1] + int(0.06 * SR))
    return a[s:e]


def synth_clips(model, cache):
    os.makedirs(cache, exist_ok=True)
    T = timeline()
    durs = {}
    for b in T['B']:
        durs[b['id']] = []
        for sp in b['speech']:
            key = hashlib.sha1(f"{os.path.basename(model)}|{LENGTH_SCALE}|{sp['say']}".encode()).hexdigest()[:16]
            raw = os.path.join(cache, f'{key}.raw.wav')
            clip = os.path.join(cache, f'{key}.wav')
            if not os.path.exists(clip):
                sh([sys.executable, '-m', 'piper', '-m', model, '-f', raw, '--length-scale', LENGTH_SCALE,
                    '--sentence-silence', '0'], input=sp['say'].encode(), capture_output=True)
                a = trim_silence(read_audio(raw))
                write_audio(clip, a)
                os.remove(raw)
            durs[b['id']].append(round(duration(clip), 3))
            sp['clip'] = clip
    with open(os.path.join(HERE, 'src', 'audio-durations.js'), 'w') as f:
        f.write('// Generated by build-audio.py: measured narration clip lengths (seconds) per sentence.\n')
        f.write('(function (root) {\n  const D = ' + json.dumps({'voice': os.path.basename(model).replace('.onnx', ''),
                                                                  'beats': durs}, indent=2).replace('\n', '\n  ') + ';\n')
        f.write("  if (typeof module !== 'undefined' && module.exports) module.exports = D;\n"
                "  else root.AUDIO_DURATIONS = D;\n})(typeof window !== 'undefined' ? window : globalThis);\n")
    return durs


def light_room(v):
    """Very light synthetic room: short decaying noise impulse, mixed about -24 dB."""
    rng = np.random.default_rng(3)
    n = int(0.22 * SR)
    t = np.arange(n) / SR
    ir = rng.standard_normal(n) * np.exp(-t / 0.05)
    ir[: int(0.008 * SR)] = 0
    ir /= np.sqrt(np.sum(ir ** 2))
    wet = np.fft.irfft(np.fft.rfft(v, len(v) + n) * np.fft.rfft(ir, len(v) + n), len(v) + n)[: len(v)]
    return v + 0.063 * wet


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--model', default=os.path.join(HERE, 'voices', 'en-us-ryan-high.onnx'))
    ap.add_argument('--outdir', default=os.path.join(HERE, 'out', 'audio'))
    args = ap.parse_args()
    if not os.path.exists(args.model):
        sys.exit(f'Piper voice model not found: {args.model} (see README: voices/)')
    os.makedirs(args.outdir, exist_ok=True)
    cache = os.path.join(HERE, 'audio-cache')

    synth_clips(args.model, cache)
    T = timeline()  # re-read with measured durations
    D = T['D']
    n = int(np.ceil(D * SR)) + SR
    voice = np.zeros(n)
    spans = []
    for b in T['B']:
        for sp in b['speech']:
            key = hashlib.sha1(f"{os.path.basename(args.model)}|{LENGTH_SCALE}|{sp['say']}".encode()).hexdigest()[:16]
            a = read_audio(os.path.join(cache, f'{key}.wav'))
            i = int(sp['start'] * SR)
            voice[i:i + len(a)] += a
            spans.append((sp['start'], sp['start'] + len(a) / SR))
    voice = light_room(voice)[: int(D * SR)]
    vraw = os.path.join(args.outdir, 'voice_raw.wav')
    write_audio(vraw, np.stack([voice, voice], axis=1))

    # two-pass loudnorm (linear) to VOICE_LUFS
    vpath = os.path.join(args.outdir, 'voice.wav')
    err = subprocess.run(['ffmpeg', '-hide_banner', '-nostats', '-i', vraw, '-af',
                          f'loudnorm=I={VOICE_LUFS}:TP=-2:LRA=11:print_format=json', '-f', 'null', '-'],
                         capture_output=True, text=True).stderr
    m = json.loads(err[err.rfind('{'):err.rfind('}') + 1])
    sh(['ffmpeg', '-y', '-loglevel', 'error', '-i', vraw, '-af',
        f"loudnorm=I={VOICE_LUFS}:TP=-2:LRA=11:measured_I={m['input_i']}:measured_TP={m['input_tp']}:"
        f"measured_LRA={m['input_lra']}:measured_thresh={m['input_thresh']}:offset={m['target_offset']}:linear=true",
        '-ar', str(SR), '-c:a', 'pcm_f32le', vpath])

    # music bed + ducking envelope from the voice clip times
    mraw = os.path.join(args.outdir, 'music_raw.wav')
    sh([sys.executable, os.path.join(HERE, 'make-music.py'), '--duration', f'{D:.3f}', '--out', mraw])
    music = read_audio(mraw, 2)[: int(D * SR)]
    rate = 100
    m_env = np.zeros(int(D * rate) + 1)
    for s, e in spans:
        m_env[int(max(0, s - 0.25) * rate):int((e + 0.35) * rate)] = 1
    gain_db = DUCK_DB * m_env
    first = min(s for s, _ in spans)
    end_beat = [b for b in T['B'] if b['scene'] == 'end'][0]
    tt = np.arange(len(gain_db)) / rate
    gain_db += CARD_BOOST_DB * ((tt < first) | (tt >= end_beat['start'] + 3.0))
    # smooth (≈0.3 s attack/release) with a moving average
    k = int(0.3 * rate)
    gain_db = np.convolve(np.pad(gain_db, (k, k), mode='edge'), np.ones(2 * k + 1) / (2 * k + 1), mode='same')[k:-k]
    g = 10 ** (np.interp(np.arange(len(music)) / SR, tt, gain_db) / 20)
    music = music * g[:, None]
    mtmp = os.path.join(args.outdir, 'music_ducked_tmp.wav')
    write_audio(mtmp, music)
    mi, _ = lufs(mtmp)
    music *= 10 ** ((MUSIC_LUFS - mi) / 20)
    mpath = os.path.join(args.outdir, 'music.wav')
    write_audio(mpath, music)
    os.remove(mtmp)

    v = read_audio(vpath, 2)
    L = min(len(v), len(music))
    mix = music[:L] + v[:L]
    peak = np.max(np.abs(mix))
    if peak > 0.89:  # keep true peaks under about -1 dBFS
        mix *= 0.89 / peak
    out = os.path.join(args.outdir, 'mix.wav')
    write_audio(out, mix)
    vi, vp = lufs(vpath)
    mi2, mp = lufs(mpath)
    xi, xp = lufs(out)
    report = {'duration': D, 'voice_lufs': vi, 'voice_peak_dbfs': vp, 'music_lufs': mi2, 'music_peak_dbfs': mp,
              'mix_lufs': xi, 'mix_peak_dbfs': xp}
    with open(os.path.join(args.outdir, 'levels.json'), 'w') as f:
        json.dump(report, f, indent=2)
    print('audio:', json.dumps(report))


if __name__ == '__main__':
    main()
